### ISSUE TITLE
dyld: Library not loaded: /usr/local/opt/glib/lib/libglib-2.0.0.dylib

### ISSUE THREAD

**Issue by DrHyde** [cross-platform-actions/openbsd-builder#8]
It looks as if Github have changed something in the last week and a bit that has made the OpenBSD builder stop working: https://github.com/DrHyde/perl-modules-Number-Phone/runs/4437455459?check_suite_focus=true

**Comment by jacob-carlborg** [comment]
Yes, I'm aware of the problem. I've reported the issue here: https://github.com/cross-platform-actions/action/issues/5. I've implemented a fix, but I'm having some problem uploading the release: https://github.com/cross-platform-actions/resources/runs/4435317503?check_suite_focus=true.

**Comment by jacob-carlborg** [comment]
Should be fixed now. You'll have to update to version [0.3.1](https://github.com/cross-platform-actions/action/releases/tag/v0.3.1). This should hopefully not happen again. All non-system provided libraries are now statically linked.

Fixed in https://github.com/cross-platform-actions/resources/commit/0679e275c44da6a585a4bf3d6e92708b26690ab8 and https://github.com/cross-platform-actions/action/commit/ecae318c389533fa39d74acea4e74349224249d6.

**Comment by DrHyde** [comment]
Thanks!
